In [1]:
%matplotlib inline

import numpy as np
import pandas as pd

import viz # curriculum example visualizations

In [188]:
n_trials = nrows = 10_000
n_dice = ncols = 3
# [1, 2, 3, 4, 5, 6]
rolls = np.random.choice(['Mon','Tues','Wed','Thur','Fri'], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([['Fri', 'Wed', 'Tues'],
       ['Thur', 'Tues', 'Wed'],
       ['Mon', 'Mon', 'Wed'],
       ...,
       ['Thur', 'Mon', 'Tues'],
       ['Wed', 'Tues', 'Fri'],
       ['Mon', 'Mon', 'Tues']], dtype='<U4')

In [3]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([ 6, 11,  5, ..., 10,  9, 15])

In [282]:
# viz.simulation_example1(sums_by_trial)

In [5]:
wins = sums_by_trial > 12
wins

array([False, False, False, ..., False, False,  True])

In [6]:
win_rate = wins.astype(int).mean()
win_rate

0.2627

In [7]:
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

-1.0595000000000003

In [8]:
wins = sums_by_trial >= 12
win_rate = wins.astype(int).mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

0.6129999999999995

In [9]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

(pd.DataFrame(rolls)
 .apply(lambda row: n_dice == n_dice in row.values, axis=1)
 .mean())

0.3051

## #1 How likely is it that you roll doubles when rolling two dice?

In [10]:
# use lambda to evaluate a condition row-wise
(pd.DataFrame(rolls).apply(lambda row: row[0] == row[1], axis =1)).mean()

0.162

In [11]:
trial = rolls.sum(axis=1)
trial

array([9, 9, 5, ..., 8, 8, 6])

## #2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [295]:
trial_n = nrows = 10_000

coin = ncols = 8

coin_flips = np.random.choice(['Heads','Tails'], trial_n * coin).reshape(nrows, ncols)

# coin_flips = np.random.choice(['Heads','Tails'], coin * trial_n)
n_heads = (coin_flips == 'Heads').sum(axis = 1)
# n_heads
(n_heads >= 3).mean()

0.8577

## #3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [296]:
#that tells me that it is 1 in 4 chance of picking a data science cohort
nrows=2
ncols=1
#the answer is 1 out of 8 chance of both being data science cohort
web_dev = 0
data_sci = 0
cohorts = web_dev + data_sci

# np.random.choice(['Web_dev','Web_dev','Web_dev','Data_sci']).mean()
#run multiple times to render a result score
#currently not running multiple times

# billboard=np.random.choice([False,False,False,True], size=1000).reshape(2, 1000)
# pd.Dataframe(billboard)
# (pd.DataFrame(billboard).apply(lambda row: row[0] == row[1], axis =1)).mean()

In [300]:
nrows=10_000
ncols=2
np.random.choice(["Web Development","Data Science"], p =[.75,.25],size=(nrows,ncols))

array([['Data Science', 'Web Development'],
       ['Data Science', 'Web Development'],
       ['Web Development', 'Web Development'],
       ...,
       ['Web Development', 'Web Development'],
       ['Data Science', 'Data Science'],
       ['Web Development', 'Web Development']], dtype='<U15')

In [14]:
# (pd.DataFrame(billboard).apply(lambda row: row[0] == row[1], axis =1)).mean()

In [15]:
billboards = 10**5
cohort = 2
sign = np.random.choice([1,0,0,0], billboards * cohort).reshape(billboards, cohort)
sign = pd.DataFrame(sign)

In [16]:
sign

0  1
0      1  0
1      0  0
2      0  0
3      0  1
4      0  0
...   .. ..
99995  0  0
99996  1  0
99997  0  0
99998  1  0
99999  0  0

[100000 rows x 2 columns]

In [17]:
sign.apply((lambda row: row.sum() ==  2 ),axis=1).mean()

0.0602

## #4 Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [293]:
#students usually by 3 poptarts give or take about 1 and a half poptart(s)
#run at squared rates of 100 similair to last problem
average = 3
standard_deviation = 1.5
#giving us about 4.5 poptarts eaten daily * 5 = 20, instinctually we see that answer is not guaranteed
#think of each day someone eats at least 3
poptarts=np.random.normal(loc=3,scale=1.5, size=(1_000_000,5)).round().astype(int)
poptarts=poptarts.sum(axis=1)
# viz.simulation_example1(poptarts)
available = poptarts >= 17
available
win_rate = available.astype(int).mean()
win_rate
#He has rough %32.9602 of him being able to get one
#so with the above code it gives me the totals of these rolls landing in a 5 day week

0.329602

In [160]:
# now i need to run it a bunch of times
# poptarts_eaten = 
billboards = 10**5
cohort = 2
poptarts = np.random.normal(loc=3,scale=1.5)
# np.random.choice(poptarts, billboards * cohort).reshape(billboards, cohort)
# maybe what i need to do instead is wrap it in a data frame

## #